title: Roberto Franceschi # your name (or website title) here
logo: "/images/profile_photo_cropped.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Aspiring Data Scientist &#x1F4CA &#x1F680
  <br><br>
  I'm a MSc Data Science and Engineering student from Polytechnic University of Turin. I'm passionate about computer science and sports.
  <br>
  <table style="border-color: #FFF!important;">
    <tr style="text-align: center;">
      <td style="text-align: right;"><a href="https://www.linkedin.com/in/roberto-franceschi/"> <i class="fa fa-linkedin fa-2x" style="color:#0e76a8;" aria-hidden="true"></i></a></td>
      <td style="text-align: left;"><a href="https://github.com/robertofranceschi"> <i class="fa fa-github fa-2x" style="color:#24292e;" aria-hidden="true"></i></a></td> 
    </tr>
  </table>
  <br><br>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
