title: Roberto Franceschi # your name (or website title) here
logo: "/images/profile_photo_cropped.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Aspiring Data Scientist &#x1F4CA &#x1F680
  <br><br>
  I'm a MSc Data Science and Engineering student from Polytechnic University of Turin. I'm passionate about computer science and sports.
  <br><br>
  <a href="https://www.linkedin.com/in/roberto-franceschi/">View My Profile</a> 
  <a href="https://www.linkedin.com/in/roberto-franceschi/"> <i class="fa fa-linkedin" aria-hidden="true"></i></a>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
